print("========================================================================================================================")
print("==  Nombre ==  Fortalezas  ==  Debilidades  ==    Gustos     == Canciones o artistas ==           Mi estado de animo   =")
print("== ================================================================================= ==                 de Hoy         =")
print("= Daniel   ==  Ser Amable  ==   //////////  ==  Videojuegos  == The winner take all  ==                   es:          =")
print("= Martinez ==  Amistoso    ==   //////////  ==  La musica    ==    No one Notice     ==           Contento y energico  =")
print("= Zepeta   ==  Obediente   ==   //////////  ==  La Tecnologi ==  World's smallest... ==                   >:)          =")
print("========================================================================================================================")
print("================================= Estas vacaciones estuve con mi familia ===============================================")
print("======================= Celebrando y pasando el tiempo con ellos en las festividades ===================================")
print("=================================== Y sali de viaje con ellos. =========================================================")
print("========================================================================================================================")